{"name": "Проверка появления сообщения об ошибки при невалидном значении", "status": "passed", "description": "Тест проверяет появление ошибки при разных невалидных значения", "steps": [{"name": "Открытие раздела Asynchronous Operation", "status": "passed", "start": 1760795518166, "stop": 1760795518286}, {"name": "Удаление значения из поля", "status": "passed", "start": 1760795518286, "stop": 1760795518361}, {"name": "Ввод значения", "status": "passed", "parameters": [{"name": "value", "value": "0"}], "start": 1760795518361, "stop": 1760795518381}, {"name": "Получение текста из сообщения об ошибки", "status": "passed", "start": 1760795518381, "stop": 1760795518395}], "parameters": [{"name": "value", "value": "0"}, {"name": "expected_message", "value": "'Please enter a number between 1 and 50'"}], "start": 1760795518166, "stop": 1760795518395, "uuid": "3bb0cce0-7e44-4aef-b5a7-2aaf8ad5f70e", "historyId": "f473534c51b4822eff77d4fbcaa54710", "testCaseId": "6ee181214c8e63f33f13238776036c26", "fullName": "tests.test_asynchronous_operation_page#test_invalid_value", "labels": [{"name": "suite", "value": "Data loading"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "OGPC214"}, {"name": "thread", "value": "22532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_asynchronous_operation_page"}], "titlePath": ["tests", "test_asynchronous_operation_page.py"]}