{"name": "Проверка появления сообщения об ошибки при невалидном значении", "status": "passed", "description": "Тест проверяет появление ошибки при разных невалидных значения", "steps": [{"name": "Открытие раздела Asynchronous Operation", "status": "passed", "start": 1760795523182, "stop": 1760795523312}, {"name": "Удаление значения из поля", "status": "passed", "start": 1760795523312, "stop": 1760795523376}, {"name": "Ввод значения", "status": "passed", "parameters": [{"name": "value", "value": "1"}], "start": 1760795523376, "stop": 1760795523396}, {"name": "Получение текста из сообщения об ошибки", "status": "passed", "start": 1760795523396, "stop": 1760795523410}], "parameters": [{"name": "value", "value": "1"}, {"name": "expected_message", "value": "''"}], "start": 1760795523182, "stop": 1760795523410, "uuid": "541a780b-9321-480f-bfe3-1c32654fbeb6", "historyId": "6b08f7fadf11092d327e02ac2f3caf93", "testCaseId": "6ee181214c8e63f33f13238776036c26", "fullName": "tests.test_asynchronous_operation_page#test_invalid_value", "labels": [{"name": "suite", "value": "Data loading"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "OGPC214"}, {"name": "thread", "value": "22532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_asynchronous_operation_page"}], "titlePath": ["tests", "test_asynchronous_operation_page.py"]}