{"name": "Проверка появления сообщения об ошибки при невалидном значении", "status": "passed", "description": "Тест проверяет появление ошибки при разных невалидных значения", "steps": [{"name": "Открытие раздела Asynchronous Operation", "status": "passed", "start": 1760795513207, "stop": 1760795513325}, {"name": "Удаление значения из поля", "status": "passed", "start": 1760795513325, "stop": 1760795513397}, {"name": "Ввод значения", "status": "passed", "parameters": [{"name": "value", "value": "51"}], "start": 1760795513398, "stop": 1760795513418}, {"name": "Получение текста из сообщения об ошибки", "status": "passed", "start": 1760795513418, "stop": 1760795513432}], "parameters": [{"name": "value", "value": "51"}, {"name": "expected_message", "value": "'Please enter a number between 1 and 50'"}], "start": 1760795513207, "stop": 1760795513432, "uuid": "f8ac775f-a514-43f1-9178-83da8fea9fa7", "historyId": "02a25c405ad27e279beb6dcb0fe76050", "testCaseId": "6ee181214c8e63f33f13238776036c26", "fullName": "tests.test_asynchronous_operation_page#test_invalid_value", "labels": [{"name": "suite", "value": "Data loading"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "OGPC214"}, {"name": "thread", "value": "22532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_asynchronous_operation_page"}], "titlePath": ["tests", "test_asynchronous_operation_page.py"]}