{"name": "Проверка появления сообщения об ошибки при невалидном значении", "status": "passed", "description": "Тест проверяет появление ошибки при разных невалидных значения", "steps": [{"name": "Открытие раздела Asynchronous Operation", "status": "passed", "start": 1760795538219, "stop": 1760795538334}, {"name": "Удаление значения из поля", "status": "passed", "start": 1760795538334, "stop": 1760795538410}, {"name": "Ввод значения", "status": "passed", "parameters": [{"name": "value", "value": "''"}], "start": 1760795538410, "stop": 1760795538433}, {"name": "Получение текста из сообщения об ошибки", "status": "passed", "start": 1760795538433, "stop": 1760795538448}], "parameters": [{"name": "value", "value": "''"}, {"name": "expected_message", "value": "'Please enter a number between 1 and 50'"}], "start": 1760795538219, "stop": 1760795538448, "uuid": "71698637-22d9-4a1f-b618-b9f0221215b5", "historyId": "74875999e449946193a24130fe163e19", "testCaseId": "6ee181214c8e63f33f13238776036c26", "fullName": "tests.test_asynchronous_operation_page#test_invalid_value", "labels": [{"name": "suite", "value": "Data loading"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "OGPC214"}, {"name": "thread", "value": "22532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_asynchronous_operation_page"}], "titlePath": ["tests", "test_asynchronous_operation_page.py"]}