{"name": "Проверка появления сообщения об ошибки при невалидном значении", "status": "passed", "description": "Тест проверяет появление ошибки при разных невалидных значения", "steps": [{"name": "Открытие раздела Asynchronous Operation", "status": "passed", "start": 1760795528180, "stop": 1760795528294}, {"name": "Удаление значения из поля", "status": "passed", "start": 1760795528294, "stop": 1760795528369}, {"name": "Ввод значения", "status": "passed", "parameters": [{"name": "value", "value": "50"}], "start": 1760795528369, "stop": 1760795528390}, {"name": "Получение текста из сообщения об ошибки", "status": "passed", "start": 1760795528390, "stop": 1760795528404}], "parameters": [{"name": "value", "value": "50"}, {"name": "expected_message", "value": "''"}], "start": 1760795528180, "stop": 1760795528404, "uuid": "71396fdf-51c8-460d-aed7-d2bf376e4a8d", "historyId": "57c5838e307df8707e49f9f038b5a2f7", "testCaseId": "6ee181214c8e63f33f13238776036c26", "fullName": "tests.test_asynchronous_operation_page#test_invalid_value", "labels": [{"name": "suite", "value": "Data loading"}, {"name": "parentSuite", "value": "tests"}, {"name": "host", "value": "OGPC214"}, {"name": "thread", "value": "22532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_asynchronous_operation_page"}], "titlePath": ["tests", "test_asynchronous_operation_page.py"]}